use_frameworks!

target 'MGProgressHUD_Example' do
  pod 'MGProgressHUD', :path => '../'

  target 'MGProgressHUD_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
